name: ClaudeCodeUsage
options:
  bundleIdPrefix: com.bml
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: false
  createIntermediateGroups: true

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: "7.9.0"

targets:
  ClaudeCodeUsage:
    type: application
    platform: macOS
    sources:
      - path: Sources/ClaudeCodeUsage
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bml.claude-code-usage
        PRODUCT_NAME: ClaudeCodeUsage
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "15.0"
        CODE_SIGN_ENTITLEMENTS: ClaudeCodeUsage.entitlements
        INFOPLIST_FILE: Info.plist
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_IDENTITY: "-"
        SWIFT_STRICT_CONCURRENCY: complete
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: XCODE_BUILD
    dependencies:
      - package: GRDB

  ClaudeCodeUsageTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests/ClaudeCodeUsageTests
    settings:
      base:
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "15.0"
        SWIFT_STRICT_CONCURRENCY: complete
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: ClaudeCodeUsage
      - package: GRDB

schemes:
  ClaudeCodeUsage:
    build:
      targets:
        ClaudeCodeUsage: all
        ClaudeCodeUsageTests: [test]
    run:
      executable: ClaudeCodeUsage
    test:
      targets:
        - ClaudeCodeUsageTests
