name: Clacal
options:
  bundleIdPrefix: com.bml
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: false
  createIntermediateGroups: true

targets:
  Clacal:
    type: application
    platform: macOS
    sources:
      - path: Sources/Clacal
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bml.clacal
        PRODUCT_NAME: Clacal
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "15.0"
        CODE_SIGN_ENTITLEMENTS: Clacal.entitlements
        INFOPLIST_FILE: Info.plist
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_IDENTITY: "Local Dev Signing"
        SWIFT_STRICT_CONCURRENCY: complete
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: XCODE_BUILD

  ClacalTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests/ClacalTests
    settings:
      base:
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "15.0"
        SWIFT_STRICT_CONCURRENCY: complete
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_IDENTITY: "Local Dev Signing"
    dependencies:
      - target: Clacal

schemes:
  Clacal:
    build:
      targets:
        Clacal: all
        ClacalTests: [test]
    run:
      executable: Clacal
    test:
      targets:
        - ClacalTests
